import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'welcome': 'Welcome back',
      'join_us': 'Join Us',
      'how_it_works': 'How it works',
      'trust': 'Trust',
      'impact': 'Impact',
      'login': 'Login',
      'register': 'Create New Account',
      'select_language': 'Select your language',
      'continue': 'Continue',
      'seller_dashboard': 'Seller Dashboard',
      'recent_activity': 'Recent Activity',
      'welcome_back_user': 'Welcome back, ',
      'discover': 'Discover',
      'browse': 'Browse',
      'orders': 'Orders',
      'favourites': 'Favourites',
      'profile': 'Profile',
      'home': 'Home',
      'deliveries': 'Deliveries',
      'verification': 'Verification',
      'ratings': 'Ratings',
      'overview': 'Overview',
      'listings': 'Listings',
      'active_listings': 'Active Listings',
      'pending_orders': 'Pending Orders',
      'avg_rating': 'Avg. Rating',
      'monthly_earnings': 'Monthly Earnings',
      'new_order_received': 'New Order Received',
      'listing_expiring_soon': 'Listing Expiring Soon',
      'payment_confirmed': 'Payment Confirmed',
      'new_feedback': 'New Feedback',
      'all': 'All',
      'free': 'Free',
      'discounted': 'Discounted',
      'meals': 'Meals',
      'bread_pastries': 'Bread & Pastries',
      'groceries': 'Groceries',
      'pet_food': 'Pet Food',
      'vegan': 'Vegan',
      'vegetarian': 'Vegetarian',
      'non_vegetarian': 'Non-Vegetarian',
      'claim_now': 'Claim Now',
      'reserve': 'Reserve',
      'availability': 'Availability',
      'today': 'Today',
      'your_badges': 'Your Badges',
      'quick_actions': 'Quick Actions',
      'view_orders': 'View Orders',
      'mins_ago': 'mins ago',
      'hours_ago': 'hours ago',
      'yesterday': 'Yesterday',
      'ends_in': 'Ends in ',
      'error_unsafe_donation': 'Safety Warning: The selected pickup window exceeds the safe consumption threshold for this food type.',
      'voice_mode_on': 'Voice mode activated. How can I help?',
      'my_profile': 'My Profile',
      'personal_info': 'Personal Information',
      'full_name': 'Full Name',
      'phone_number': 'Phone Number',
      'address': 'Address',
      'vehicle_type': 'Vehicle Type',
      'bicycle': 'Bicycle',
      'bike': 'Bike',
      'car': 'Car',
      'save_changes': 'Save Changes',
      'security': 'Security',
      'new_password': 'New Password',
      'confirm_new_password': 'Confirm New Password',
      'change_password': 'Change Password',
      'logout_btn': 'Logout',
      'my_deliveries': 'My Deliveries',
      'new_requests': 'New Requests',
      'active': 'Active',
      'completed': 'Completed',
      'view_details': 'View Details',
      'accept_delivery': 'Accept Delivery',
      'pickup': 'Pickup',
      'delivery_label': 'Delivery',
      'inactive_msg': 'You are currently inactive.\nTurn on availability to receive deliveries and view performance.',
      'new_requests_banner': 'You have 2 new delivery requests waiting!',
      'verified_volunteer': 'Verified Volunteer',
      'top_volunteer': 'Top Volunteer',
      'fifty_deliveries': '50 Deliveries',
      'perfect_streak': 'Perfect Streak',
    },
    'hi': {
      'welcome': 'वापस स्वागत है',
      'join_us': 'हमसे जुड़ें',
      'how_it_works': 'यह कैसे काम करता है',
      'trust': 'भरोसा',
      'impact': 'प्रभाव',
      'login': 'लॉगिन',
      'register': 'नया खाता बनाएं',
      'select_language': 'अपनी भाषा चुनें',
      'continue': 'जारी रखें',
      'seller_dashboard': 'विक्रेता डैशबोर्ड',
      'recent_activity': 'हाल की गतिविधि',
      'welcome_back_user': 'वापस स्वागत है, ',
      'discover': 'खोजें',
      'browse': 'ब्राउज़ करें',
      'orders': 'ऑर्डर',
      'favourites': 'पसंदीदा',
      'profile': 'प्रोफ़ाइल',
      'home': 'होम',
      'deliveries': 'डिलिवरी',
      'verification': 'सत्यापन',
      'ratings': 'रेटिंग',
      'overview': 'सिंहावलोकन',
      'listings': 'लिस्टिंग',
      'active_listings': 'सक्रिय लिस्टिंग',
      'pending_orders': 'लंबित ऑर्डर',
      'avg_rating': 'औसत रेटिंग',
      'monthly_earnings': 'मासिक कमाई',
      'new_order_received': 'नया ऑर्डर प्राप्त हुआ',
      'listing_expiring_soon': 'लिस्टिंग जल्द ही समाप्त होने वाली है',
      'payment_confirmed': 'भुगतान की पुष्टि हो गई',
      'new_feedback': 'नई प्रतिक्रिया',
      'all': 'सभी',
      'free': 'मुफ्त',
      'discounted': 'छूट',
      'meals': 'भोजन',
      'bread_pastries': 'ब्रेड और पेस्ट्री',
      'groceries': 'किराना',
      'pet_food': 'पालतू भोजन',
      'vegan': 'शाकाहारी (वीगन)',
      'vegetarian': 'शाकाहारी',
      'non_vegetarian': 'मांसाहारी',
      'claim_now': 'अभी प्राप्त करें',
      'reserve': 'आरक्षित करें',
      'availability': 'उपलब्धता',
      'today': 'आज',
      'your_badges': 'आपके बैज',
      'quick_actions': 'त्वरित कार्य',
      'view_orders': 'ऑर्डर देखें',
      'mins_ago': 'मिनट पहले',
      'hours_ago': 'घंटे पहले',
      'yesterday': 'कल',
      'ends_in': 'समाप्त होगा ',
      'error_unsafe_donation': 'सुरक्षा चेतावनी: चयनित पिकअप विंडो इस प्रकार के भोजन के लिए सुरक्षित उपभोग सीमा से अधिक है।',
      'voice_mode_on': 'वॉयस मोड सक्रिय। मैं आपकी क्या मदद कर सकता हूँ?',
      'my_profile': 'मेरी प्रोफ़ाइल',
      'personal_info': 'व्यक्तिगत जानकारी',
      'full_name': 'पूरा नाम',
      'phone_number': 'फोन नंबर',
      'address': 'पता',
      'vehicle_type': 'वाहन का प्रकार',
      'bicycle': 'साइकिल',
      'bike': 'बाइक',
      'car': 'कार',
      'save_changes': 'बदलाव सहेजें',
      'security': 'सुरक्षा',
      'new_password': 'नया पासवर्ड',
      'confirm_new_password': 'नए पासवर्ड की पुष्टि करें',
      'change_password': 'पासवर्ड बदलें',
      'logout_btn': 'लॉगआउट',
      'my_deliveries': 'मेरी डिलीवरी',
      'new_requests': 'नए अनुरोध',
      'active': 'सक्रिय',
      'completed': 'पूरा हुआ',
      'view_details': 'विवरण देखें',
      'accept_delivery': 'डिलीवरी स्वीकार करें',
      'pickup': 'पिकअप',
      'delivery_label': 'डिलीवरी',
      'inactive_msg': 'आप वर्तमान में निष्क्रिय हैं।\nडिलीवरी प्राप्त करने और प्रदर्शन देखने के लिए उपलब्धता चालू करें।',
      'new_requests_banner': 'आपके पास 2 नए डिलीवरी अनुरोध प्रतीक्षारत हैं!',
      'verified_volunteer': 'सत्यापित स्वयंसेवक',
      'top_volunteer': 'शीर्ष स्वयंसेवक',
      'fifty_deliveries': '50 डिलीवरी',
      'perfect_streak': 'परफेक्ट स्ट्रीక',
    },
    'ta': {
      'welcome': 'மீண்டும் வருக',
      'join_us': 'எங்களுடன் இணையுங்கள்',
      'how_it_works': 'இது எப்படி வேலை செய்கிறது',
      'trust': 'நம்பிக்கை',
      'impact': 'தாக்கம்',
      'login': 'உள்நுழைக',
      'register': 'புதிய கணக்கை உருவாக்கு',
      'select_language': 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
      'continue': 'தொடரவும்',
      'seller_dashboard': 'விற்பனையாளர் டாஷ்போர்டு',
      'recent_activity': 'சமீபத்திய செயல்பாடு',
      'welcome_back_user': 'மீண்டும் வருக, ',
      'discover': 'கண்டுபிடி',
      'browse': 'உலவு',
      'orders': 'ஆர்டர்கள்',
      'favourites': 'விருப்பமானவை',
      'profile': 'சுயவிவரம்',
      'home': 'முகப்பு',
      'deliveries': 'டெலிவரிகள்',
      'verification': 'சரிபார்ப்பு',
      'ratings': 'மதிப்பீடுகள்',
      'overview': 'கண்ணோட்டம்',
      'listings': 'பட்டியல்கள்',
      'active_listings': 'செயலில் உள்ள பட்டியல்கள்',
      'pending_orders': 'நிலுவையில் உள்ள ஆர்டர்கள்',
      'avg_rating': 'சராசரி மதிப்பீடு',
      'monthly_earnings': 'மாதாந்திர வருமானம்',
      'new_order_received': 'புதிய ஆர்டர் பெறப்பட்டது',
      'listing_expiring_soon': 'பட்டியல் விரைவில் காலாவதியாகிறது',
      'payment_confirmed': 'பணம் செலுத்துதல் உறுதி செய்யப்பட்டது',
      'new_feedback': 'புதிய கருத்து',
      'all': 'அனைத்தும்',
      'free': 'இலவசம்',
      'discounted': 'தள்ளுபடி',
      'meals': 'உணவுகள்',
      'bread_pastries': 'ரொட்டி மற்றும் பேஸ்ட்ரிகள்',
      'groceries': 'மளிகைப் பொருட்கள்',
      'pet_food': 'செல்லப்பிராணி உணவு',
      'vegan': 'சைவம் (வீகன்)',
      'vegetarian': 'சைவம்',
      'non_vegetarian': 'அசைவம்',
      'claim_now': 'இப்போது பெறுங்கள்',
      'reserve': 'முன்பதிவு செய்',
      'availability': 'கிடைக்கும் தன்மை',
      'today': 'இன்று',
      'your_badges': 'உங்கள் பேட்ஜ்கள்',
      'quick_actions': 'விரைவான செயல்கள்',
      'view_orders': 'ஆர்டர்களைப் பார்',
      'mins_ago': 'நிமிடங்களுக்கு முன்பு',
      'hours_ago': 'மணிநேரங்களுக்கு முன்பு',
      'yesterday': 'நேற்று',
      'ends_in': 'முடிவடைகிறது ',
      'error_unsafe_donation': 'பாதுகாப்பு எச்சரிக்கை: தேர்ந்தெடுக்கப்பட்ட பிக்கப் சாளரம் இந்த வகை உணவிற்கான பாதுகாப்பான நுகர்வு வரம்பை மீறுகிறது.',
      'voice_mode_on': 'குரல் பயன்முறை செயல்படுத்தப்பட்டது. நான் உங்களுக்கு எப்படி உதவ முடியும்?',
      'my_profile': 'எனது சுயவிவரம்',
      'personal_info': 'தனிப்பட்ட தகவல்',
      'full_name': 'முழு பெயர்',
      'phone_number': 'தொலைபேசி எண்',
      'address': 'முகவரி',
      'vehicle_type': 'வாகன வகை',
      'bicycle': 'மிதிவண்டி',
      'bike': 'பைக்',
      'car': 'கார்',
      'save_changes': 'மாற்றங்களைச் சேமிக்கவும்',
      'security': 'பாதுகாப்பு',
      'new_password': 'புதிய கடவுச்சொல்',
      'confirm_new_password': 'புதிய கடவுச்சொல்லை உறுதிப்படுத்தவும்',
      'change_password': 'கடவுச்சொல்லை மாற்றவும்',
      'logout_btn': 'வெளியேறு',
      'my_deliveries': 'எனது டெலிவரிகள்',
      'new_requests': 'புதிய கோரிக்கைகள்',
      'active': 'செயல்பாட்டில் உள்ளது',
      'completed': 'முடிந்தது',
      'view_details': 'விவரங்களைக் காண்க',
      'accept_delivery': 'டெலிவரியை ஏற்கவும்',
      'pickup': 'பிக்கப்',
      'delivery_label': 'டெலிவரி',
      'inactive_msg': 'நீங்கள் தற்போது செயலில் இல்லை.\nடெலிவரிகளைப் பெறவும் செயல்திறனைப் பார்க்கவும் கிடைக்கும் தன்மையை (availability) இயக்கவும்.',
      'new_requests_banner': 'உங்களிடம் 2 புதிய டெலிவரி கோரிக்கைகள் உள்ளன!',
      'verified_volunteer': 'சரிபார்க்கப்பட்ட தன்னார்வலர்',
      'top_volunteer': 'சிறந்த தன்னார்வலர்',
      'fifty_deliveries': '50 டெலிவரிகள்',
      'perfect_streak': 'சரியான தொடர்ச்சி',
    },
    'te': {
      'welcome': 'తిరిగి స్వాగతం',
      'join_us': 'మాతో చేరండి',
      'how_it_works': 'ఇది ఎలా పనిచేస్తుంది',
      'trust': 'నమ్మకం',
      'impact': 'ప్రభావం',
      'login': 'లాగిన్',
      'register': 'కొత్త ఖాతాను సృష్టించు',
      'select_language': 'మీ భాషను ఎంచుకోండి',
      'continue': 'కొనసాగించు',
      'seller_dashboard': 'విక్రేత డాష్‌బోర్డ్',
      'recent_activity': 'ఇటీవలి కార్యాచరణ',
      'welcome_back_user': 'తిరిగి స్వాగతం, ',
      'discover': 'కనుగొనండి',
      'browse': 'బ్రౌజ్ చేయండి',
      'orders': 'ఆర్డర్లు',
      'favourites': 'ఇష్టమైనవి',
      'profile': 'ప్రొఫైల్',
      'home': 'హోమ్',
      'deliveries': 'డెలివరీలు',
      'verification': 'ధృవీకరణ',
      'ratings': 'రేటింగ్‌లు',
      'overview': 'అవలోకనం',
      'listings': 'జాబితాలు',
      'active_listings': 'క్రియాశీల జాబితాలు',
      'pending_orders': 'పెండింగ్ ఆర్డర్లు',
      'avg_rating': 'సగటు రేటింగ్',
      'monthly_earnings': 'నెలవారీ ఆదాయం',
      'new_order_received': 'కొత్త ఆర్డర్ వచ్చింది',
      'listing_expiring_soon': 'జాబితా త్వరలో ముగుస్తుంది',
      'payment_confirmed': 'చెల్లింపు ధృవీకరించబడింది',
      'new_feedback': 'కొత్త అభిప్రాయం',
      'all': 'అన్నీ',
      'free': 'ఉచితం',
      'discounted': 'తగ్గింపు',
      'meals': 'భోజనం',
      'bread_pastries': 'బ్రెడ్ & పేస్ట్రీలు',
      'groceries': 'కిరాణా సరుకులు',
      'pet_food': 'పెంపుడు జంతువుల ఆహారం',
      'vegan': 'వీగన్',
      'vegetarian': 'శాకాహారం',
      'non_vegetarian': 'మాంసాహారం',
      'claim_now': 'ఇప్పుడే పొందండి',
      'reserve': 'రిజర్వ్ చేయండి',
      'availability': 'అందుబాటు',
      'today': 'నేడు',
      'your_badges': 'మీ బ్యాడ్జ్‌లు',
      'quick_actions': 'త్వరిత చర్యలు',
      'view_orders': 'ఆర్డర్‌లను చూడండి',
      'mins_ago': 'నిమిషాల క్రితం',
      'hours_ago': 'గంటల క్రితం',
      'yesterday': 'నిన్న',
      'ends_in': 'ముగిసే సమయం ',
      'error_unsafe_donation': 'భద్రతా హెచ్చరిక: ఎంచుకున్న పికప్ విండో ఈ రకమైన ఆహారం కోసం సురక్షితమైన వినియోగ పరిమితిని మించిపోయింది.',
      'voice_mode_on': 'వాయిస్ మోడ్ యాక్టివేట్ చేయబడింది. నేను మీకు ఎలా సహాయం చేయగలను?',
      'my_profile': 'నా ప్రొఫైల్',
      'personal_info': 'వ్యక్తిగత సమాచారం',
      'full_name': 'పూర్తి పేరు',
      'phone_number': 'ఫోన్ నంబర్',
      'address': 'చిరునామా',
      'vehicle_type': 'వాహనం రకం',
      'bicycle': 'సైకిల్',
      'bike': 'బైక్',
      'car': 'కారు',
      'save_changes': 'మార్పులను సేవ్ చేయండి',
      'security': 'భద్రత',
      'new_password': 'కొత్త పాస్‌వర్డ్',
      'confirm_new_password': 'కొత్త పాస్‌వర్డ్ ని ధృవీకరించండి',
      'change_password': 'పాస్‌వర్డ్ మార్చు',
      'logout_btn': 'లాగ్ అవుట్',
      'my_deliveries': 'నా డెలివరీలు',
      'new_requests': 'కొత్త అభ్యర్థనలు',
      'active': 'యాక్టివ్',
      'completed': 'పూర్తయింది',
      'view_details': 'వివరాలను చూడండి',
      'accept_delivery': 'డెలివరీని అంగీకరించు',
      'pickup': 'పికప్',
      'delivery_label': 'డెలివరీ',
      'inactive_msg': 'మీరు ప్రస్తుతం నిష్క్రియంగా ఉన్నారు.\nడెలివరీలను స్వీకరించడానికి మరియు పనితీరును చూడటానికి అందుబాటును ఆన్ చేయండి.',
      'new_requests_banner': 'మీకు 2 కొత్త డెలివరీ అభ్యర్థనలు వేచి ఉన్నాయి!',
      'verified_volunteer': 'ధృవీకరించబడిన వాలంటీర్',
      'top_volunteer': 'టాప్ వాలంటీర్',
      'fifty_deliveries': '50 డెలివరీలు',
      'perfect_streak': 'పర్ఫెక్ట్ స్ట్రీక్',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'hi', 'ta', 'te'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
